const getWord = () => {
  const adjectives = [
    "Apple",
    "Banana",
    "Mango",
    "Watermelon",
    "Orange",
    "Pizza",
    "Burger",
    "Biryani",
    "Samosa",
    "Pakora",
    "Fries",
    "Ice Cream",
    "Cake",
    "Chocolate",
    "Tea",
    "Coffee",
    "Bottle",
    "Cup",
    "Plate",
    "Spoon",
    "Chair",
    "Table",
    "Bed",
    "Fan",
    "Clock",
    "Phone",
    "Laptop",
    "Keyboard",
    "Mouse",
    "Headphones",
    "Camera",
    "Television",
    "Book",
    "Pen",
    "Pencil",
    "Bag",
    "School",
    "University",
    "Classroom",
    "Teacher",
    "Student",
    "Doctor",
    "Police",
    "Soldier",
    "Shopkeeper",
    "Driver",
    "Football",
    "Cricket",
    "Bat",
    "Ball",
    "Stumps",
    "Bike",
    "Car",
    "Bus",
    "Rickshaw",
    "Train",
    "Airplane",
    "Bicycle",
    "House",
    "Mosque",
    "Shop",
    "Hospital",
    "Park",
    "Road",
    "Bridge",
    "Tree",
    "Flower",
    "Mountain",
    "River",
    "Sun",
    "Moon",
    "Star",
    "Cloud",
    "Rain",
    "Umbrella",
    "Rainbow",
    "Fire",
    "Snowman",
    "Cat",
    "Dog",
    "Lion",
    "Tiger",
    "Elephant",
    "Monkey",
    "Horse",
    "Cow",
    "Goat",
    "Chicken",
    "Fish",
    "Bird",
    "Snake",
    "Butterfly",
    "Spider",
    "Robot",
    "Alien",
    "Ghost",
    "Monster",
    "King",
    "Queen",
    "Superhero",
    "Pirate",
    "Ninja",
    "Police Car",
    "Ambulance",
    "Fire Truck",
    "Rocket",
    "Helicopter",
    "Crown",
    "Sword",
    "Shield",
    "Treasure",
    "Key",
    "Lock",
    "Balloon",
    "Gift",
    "Birthday Cake",
    "Football Goal",
    "Cricket Bat",
    "Traffic Light",
    "Stop Sign",
    "Traffic Police",
    "Mobile Charger",
    "Backpack",
    "Sunglasses",
    "Watch",
    "Wallet",
    "Money",
    "Coin",
    "Umbrella",
    "Toothbrush",
    "Soap",
    "Mirror",
    "Bed",
    "Pillow",
    "Door",
    "Window",
    "House Key",
    "Computer",
    "Printer",
    "Calculator",
    "USB",
    "WiFi",
    "Internet",
    "Password",
    "Game Controller",
    "Minecraft",
    "YouTube",
    "WhatsApp",
    "Instagram",
    "TikTok",
    "Emoji",
    "Smile",
    "Heart",
    "Angry Face",
    "Crying Face",
    "Laughing Face",
    "Thumbs Up",
    "Broken Heart",
    "Wedding",
    "Birthday",
    "Exam",
    "Homework",
    "Graduation",
    "Vacation",
    "Beach",
    "Swimming Pool",
    "Gym",
    "Football Match",
    "Cricket Match",
    "Traffic Jam",
    "Rainy Day",
    "Power Outage",
    "Load Shedding",
    "Eid",
    "Eid Moon",
    "Eid Prayer",
    "Rickshaw",
    "Chai Dhaba",
    "Biryani Plate",
    "Samosa",
    "Naan",
    "Paratha",
    "Lassi",
    "Chai",
    "Cricket Player",
    "Cricket Umpire",
    "Pakistani Flag",
    "Minar-e-Pakistan",
    "Badshahi Mosque",
    "Truck Art"
  ];

  return adjectives[Math.floor(Math.random() * adjectives.length)];
};

module.exports = getWord;